/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Gentle Start',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 100,
      obstacleCount: 3,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Bouncing Platforms',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 90,
      targetScore: 150,
      obstacleCount: 4,
      obstacleSpeed: 2,
      collectibleCount: 8,
      collectibleValue: 20,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Spinning Platforms',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 120,
      targetScore: 200,
      obstacleCount: 6,
      obstacleSpeed: 3,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Challenging Maze',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 180,
      targetScore: 300,
      obstacleCount: 8,
      obstacleSpeed: 4,
      collectibleCount: 12,
      collectibleValue: 30,
      backgroundTheme: 'ancient_ruins',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Speeding Platforms',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 150,
      targetScore: 400,
      obstacleCount: 10,
      obstacleSpeed: 5,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'ancient_ruins',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Treacherous Abyss',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 120,
      targetScore: 500,
      obstacleCount: 12,
      obstacleSpeed: 6,
      collectibleCount: 10,
      collectibleValue: 40,
      backgroundTheme: 'dark_cavern',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Shifting Platforms',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 180,
      targetScore: 600,
      obstacleCount: 14,
      obstacleSpeed: 7,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'dark_cavern',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Treacherous Labyrinth',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 210,
      targetScore: 700,
      obstacleCount: 16,
      obstacleSpeed: 8,
      collectibleCount: 15,
      collectibleValue: 50,
      backgroundTheme: 'futuristic_city',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Perilous Peaks',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 240,
      targetScore: 800,
      obstacleCount: 18,
      obstacleSpeed: 9,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'futuristic_city',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Apex Challenge',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: null,
      targetScore: 1000,
      obstacleCount: 20,
      obstacleSpeed: 10,
      collectibleCount: 20,
      collectibleValue: 60,
      backgroundTheme: 'futuristic_city',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
